# Generated by Django 3.1.1 on 2020-09-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='book_name',
            new_name='book',
        ),
    ]
