# Generated by Django 3.1.1 on 2020-09-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_pdf', '0002_auto_20200925_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '书籍类别', 'verbose_name_plural': '书籍类别'},
        ),
    ]
