# Generated by Django 3.1.1 on 2020-09-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_pdf', '0003_auto_20200925_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_size',
            field=models.FloatField(verbose_name='书籍大小'),
        ),
    ]
